// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:warranty_tracker/data/models/product_document_hive_model.dart';
import 'package:warranty_tracker/data/models/service_record_hive_model.dart';
import 'package:warranty_tracker/data/models/warranty_item_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ProductDocumentHiveModelAdapter());
    registerAdapter(ServiceRecordHiveModelAdapter());
    registerAdapter(WarrantyItemHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ProductDocumentHiveModelAdapter());
    registerAdapter(ServiceRecordHiveModelAdapter());
    registerAdapter(WarrantyItemHiveModelAdapter());
  }
}
